name: Carbon2
main: com.lastabyss.carbon.Carbon
description: Adds future Minecraft features into older Spigot versions
softdepend: []
loadbefore: [LWC, NoCheatPlus, NoCheatPlusCompat]
load: STARTUP
version: 2.0
authors: [Navid K., _Shevchik_, Aust1n46, PatoTheBest]

commands:
  carbon:
    description: Carbon mod command.
    usage: /<command> [argument]
